### ISSUE TITLE
No operators unlocked in seasons after Y8S2

### ISSUE THREAD

**Issue by bb-ites** [SlejmUr/Manifest_Tool_TB#5]
There seem to be no operators available to play besides recruit in Heavy Mettle, Deep Freeze, and Deadly Omen 
![355627322-dfab61d4-f7da-4ab4-8177-07b9813f8bab](https://github.com/user-attachments/assets/2df2547d-1642-4534-8573-6b386c71e8fd)
![355627197-413ba11f-ec2d-44f2-908e-576db49fbbba](https://github.com/user-attachments/assets/6e15e3b4-9f36-43ad-ad59-8f85908df789)

**Comment by SlejmUr** [comment]
try complete the Tutorial or something i think after this it might unlock

**Comment by bb-ites** [comment]
this was after the tutorial was done

**Comment by SlejmUr** [comment]
cant do anything with it
